### ISSUE TITLE
gsplat version issue

### ISSUE THREAD

**Issue by Xzzit** [Linusnie/render-splats#1]
Thank you for your great illustration! I wanted to let you know that gsplat has been updated to [v0.1.11](https://github.com/nerfstudio-project/gsplat/releases/tag/v0.1.11), which has caused some functions to change:
1. The `viewmat` parameter has been removed from `gsplat.project_gaussians`.

Could you please update the code accordingly? I'm currently struggling with the transformation conversion, and your help would be immensely beneficial!

Thank you so much!

**Comment by Linusnie** [comment]
hi, thanks for the heads up. Just removing the `projmat` input solves the issue on my side

**Comment by Xzzit** [comment]
Thank you for your reply! I have resolved the issue.

I intended to render images using the original Gaussian Splatting's dataloader and pipeline. However, I encountered some weried operations that caused rendering to fail when using gsplat directly.

In Gaussian Splatting, the W2C matrix is transposed, which results in a critical failure when rendering a pretrained Gaussian Splatting model.

To help others who might face the same problem, I’m sharing the fixed code here:

```
    means2d, depths, radii, conics, compensation, num_tiles_hit, cov3d = gsplat.project_gaussians(
        means3d = gaussians.get_xyz,
        scales = gaussians.get_scaling,
        glob_scale = 1.,
        quats = gaussians.get_rotation,
        viewmat = view.world_view_transform.transpose(0, 1),
        fx = fov2focal(view.FoVx, view.image_width),
        fy = fov2focal(view.FoVy, view.image_height),
        cx = view.image_width / 2,
        cy = view.image_height / 2,
        img_height = round(view.image_height / resolution_factor),
        img_width = round(view.image_width / resolution_factor),
        block_width = 16,
        clip_thresh = 0.01,
    )
```

**Comment by Linusnie** [comment]
@Xzzit I've just pushed another commit which should fix the issue. I also spotted that the `view_dirs` variable was facing the wrong direction, causing some color artifacts in the gsplat render. Should work better now!
